### ISSUE TITLE
No proper documentation for public methods to detect mrz from already captured images (Bitmaps) 

### ISSUE THREAD

**Issue by mani516** [accurascan/Android-KYC#15]
Hello,

We are trying the latest version of the library for MRZ Scan usecase. Everything is working fine.

However, we have another usecase where the sdk should find mrz from already captured image, instead of it being scanned by this library.

In previous versions, there used to be the following method in RecogEngine class

`public int doRunBitmap(Bitmap bitmap, int facepick, int rot, RecogResult result) { }`

which we were using with the already captured image.

But with the latest sdk, some overloaded public method is there, but the parameters of this method are unclear.
`private native int doRecogBitmap(Bitmap var1, int var2, int[] var3, Bitmap var4, int[] var5, boolean var6, int var7, String var8);`

Also tried other public methods,

-     `public void a(final Bitmap var1, final int var2, final int var3, final RecogResult var4) {}`
-     `public int a(Bitmap var1, RecogResult var2, MRZDocumentType var3, String var4) {}`

Nothing found useful because of the unclear parameter names.

We would like to know if there is any way to achieve this... or atleast point us to documentation of above public methods if possible...

**Comment by accurascan** [comment]
Hello @mani516 

We have updated our SDK and it no longer supports already captured images, currently we only support scanning of card using the device camera.

Let us discuss further on mail so that we can assist you with an modified SDK.
